# Generated by Django 5.0.6 on 2024-05-21 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_images_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='images',
            new_name='Image',
        ),
    ]
