# Generated by Django 5.0.6 on 2024-06-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_banner_name_alter_banner_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner',
            field=models.ImageField(upload_to='banners/'),
        ),
    ]
