# Generated by Django 5.0.6 on 2024-06-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_banner_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='link',
            new_name='button_link',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='banner',
            new_name='image',
        ),
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
